defaults:
 - _self_
 - codecs: default
 - data_subsets: all_files

bitrate: 128000
resample_fullband: True # Resamples 44.1 to 48 kHz

metadata_file: None


# If set to true, only a small subset of 100 random files is used
test_run: False